Update trusted application tutorial
iExecBlockchainComputing/documentation-old pull request #43
Opened 2020-06-30 12:46 UTC by zguesmi

2020-07-01 13:08 UTC, Amxx commented on for-developers/confidential-computing/create-your-first-sgx-app.md
> +As we mentioned earlier, the advantage of using **SCONE** is the ability to make the application **Intel SGX-enabled** without changing the source code. The only thing we are going to modify is the `
Intel® SGX

2020-07-01 13:09 UTC, Amxx commented on for-developers/confidential-computing/create-your-first-sgx-app.md
> +As we mentioned earlier, the advantage of using **SCONE** is the ability to make the application **Intel SGX-enabled** without changing the source code. The only thing we are going to modify is the `
`node` \(or `python`\)

2020-07-01 13:10 UTC, Amxx commented on for-developers/confidential-computing/create-your-first-sgx-app.md
> +As we mentioned earlier, the advantage of using **SCONE** is the ability to make the application **Intel SGX-enabled** without changing the source code. The only thing we are going to modify is the `
`nodejs`/`python`

2020-07-01 13:25 UTC, PierreJeanjacquot requested changes
use `IEXEC_DATASET_FILENAME`

2020-07-01 13:25 UTC, PierreJeanjacquot commented on for-developers/confidential-computing/sgx-encrypted-dataset.md
> +if (fs.existsSync(iexec_in + '/dataset.txt')) {
dataset file name is accessible through env `IEXEC_DATASET_FILENAME`

2020-07-01 13:25 UTC, PierreJeanjacquot commented on for-developers/confidential-computing/sgx-encrypted-dataset.md
> +if os.path.exists(iexec_in + '/dataset.txt'):
same here

2020-07-01 14:10 UTC, zguesmi commented on for-developers/confidential-computing/create-your-first-sgx-app.md
> +As we mentioned earlier, the advantage of using **SCONE** is the ability to make the application **Intel SGX-enabled** without changing the source code. The only thing we are going to modify is the `
Done, thanks!

2020-07-01 14:24 UTC, zguesmi commented on for-developers/confidential-computing/sgx-encrypted-dataset.md
> +if (fs.existsSync(iexec_in + '/dataset.txt')) {
Thanks :+1:

2020-07-03 11:44 UTC, james-toussaint approved these changes

2020-07-03 14:33 UTC, PierreJeanjacquot approved these changes

2020-07-03 14:35 UTC, merged