ship to prod
iExecBlockchainComputing/documentation-old pull request #88
Opened 2021-12-20 15:55 UTC by PierreJeanjacquot

2021-12-20 15:59 UTC, PierreJeanjacquot commented
preview: https://documentations.iex.ec/staging

2021-12-20 16:30 UTC, jeremyjams approved these changes

2021-12-20 16:30 UTC, jeremyjams commented on help/migration.md
> +Application developers needs to publish their application sell order to the v7 marketplace in order to make it availlable for requesters.
```suggestion
Application developers needs to publish their application sell order to the v7 marketplace in order to make it available for requesters.
```

2021-12-20 16:30 UTC, jeremyjams commented on help/migration.md
> +Dataset developers needs to push their dataset secret to the v7 SMS and publish their dataset sell order to the v7 marketplace in order to make it availlable for requesters.
```suggestion
Dataset developers needs to push their dataset secret to the v7 SMS and publish their dataset sell order to the v7 marketplace in order to make it available for requesters.
```

2021-12-21 10:37 UTC, PierreJeanjacquot commented on help/migration.md
> +Application developers needs to publish their application sell order to the v7 marketplace in order to make it availlable for requesters.
#90

2021-12-21 10:37 UTC, PierreJeanjacquot commented on help/migration.md
> +Dataset developers needs to push their dataset secret to the v7 SMS and publish their dataset sell order to the v7 marketplace in order to make it availlable for requesters.
#90

2021-12-21 13:26 UTC, ericr6 requested changes

2021-12-21 13:26 UTC, ericr6 commented on for-developers/v6-to-v7-migration.md
> +Application developers needs to publish their application sell order to the v7 marketplace in order to makes it availlable for requesters.
needs -> need
availlable -> available

2021-12-21 13:27 UTC, luisccastillo approved these changes

2021-12-21 13:30 UTC, ericr6 approved these changes

2021-12-21 13:33 UTC, PierreJeanjacquot commented on for-developers/v6-to-v7-migration.md
> +Application developers needs to publish their application sell order to the v7 marketplace in order to makes it availlable for requesters.
#90

2021-12-21 13:34 UTC, merged